[ui]
hideTopBar = false
hideSidebarNav = false  # Toon de standaard streamlit navigatie

[server]
enableStaticServing = true

[theme]
primaryColor = "#F63366"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"
